name: Build HashInsight RemoteCollector Windows EXE

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install -U pip wheel
          python -m pip install -r requirements.txt
          # Install PyInstaller explicitly; we'll invoke it via python -m to avoid PATH issues
          python -m pip install -U pyinstaller

      - name: Build EXE (PyInstaller)
        shell: pwsh
        run: |
          python -m PyInstaller --noconfirm HashInsight RemoteCollector.spec

          if (Test-Path "dist\HashInsight RemoteCollector.exe") {
            $exePath = "dist\HashInsight RemoteCollector.exe"
          } elseif (Test-Path "dist\HashInsight RemoteCollector\HashInsight RemoteCollector.exe") {
            $exePath = "dist\HashInsight RemoteCollector\HashInsight RemoteCollector.exe"
          } else {
            Write-Host "dist folder content:"
            Get-ChildItem -Recurse dist | Format-List
            throw "HashInsight RemoteCollector.exe not found in dist/"
          }

          New-Item -ItemType Directory -Force -Path artifact | Out-Null
          Copy-Item $exePath -Destination artifact\HashInsight RemoteCollector.exe -Force
          Write-Host "EXE packaged at artifact\HashInsight RemoteCollector.exe"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: HashInsight RemoteCollector-windows-exe
          path: artifact/HashInsight RemoteCollector.exe
          if-no-files-found: error
